spring:
   profiles:
      active:
      - dev

spring:
   profiles: dev   # 开发环境
   application:
      name: microservicecloud-config-jx-dev

spring:
   profiles: test   # 测试环境
   application:
      name: microservicecloud-config-jx-test

# 注意保存为UTF-8格式，否则中文乱码