spring:
   profiles:
      active:
      - dev
# dev 与 test 连接的数据库不同
---   
server:
  port: 8001
spring:
   profile: dev
   application:
    name: microservicecloud-config-dept-client                 # 应用名称，注册进eureka时会使用该名称（自动转换为大写）
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jx.springcloud.entity		    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
      
eureka:
   client: # 客户端注册进eureka服务列表内      
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka
   instance: 
      instance-id: microservicecloud-dept8001  # 修改主机映射名称
      prefer-ip-address: true  # 让访问路径可以显示IP地址(而不是localhost)
      
info:
   app.name: jx-microservicecloud-springcloudconfig-dev
   company.name: www.jx.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server:
  port: 8001
spring:
   profile: test
   application:
    name: microservicecloud-config-dept-client                 # 应用名称，注册进eureka时会使用该名称（自动转换为大写）
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jx.springcloud.entity		    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
      
eureka:
   client: # 客户端注册进eureka服务列表内      
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka
   instance: 
      instance-id: microservicecloud-dept8001  # 修改主机映射名称
      prefer-ip-address: true  # 让访问路径可以显示IP地址(而不是localhost)
      
info:
   app.name: jx-microservicecloud-springcloudconfig-test
   company.name: www.jx.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$